# Generated by Django 4.2.1 on 2023-06-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_dialogue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='openai_id',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
